import Head from 'next/head'
import Container from '../components/container/container'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>First page in next js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="main">
        <h1>First page in next js</h1>
        <h3>Hello World!</h3>
      </main>
    </Container>
  )
}
