import Head from 'next/head'
import Container from '../components/container/container'
export default function Home() {

  return (
    <Container>
      <Head>
        <title>First page in next js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      

    </Container>
  )
}
