import Link from 'next/link'
import Head from 'next/head'
import Container from '../../components/container/container'
import Button from '../../components/button/button'

export default function Movies() {
  return (
    <Container>
      <Head>
        <title>Page movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Movies</h1>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
        voluptatem, doloremque, quibusdam quisquam dolorum, quidem
        necessitatibus, quam quisquam quis, quisquam quisquam.
      </p>{' '}

      <Link href="/movies/create">
        <Button className="button" disabled={false} type="button" onClick={() => {}}>
          Create
        </Button>
      </Link>
    </Container>
  )
}